### ISSUE TITLE
회원가입 기능 /user/register

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#1]
## 사용자가 어떤 정보를 입력해야하는가 (폼)
- ID : 한글10글자? 영어 20글자? 겹치지 않게
- PW :  영어+숫자 20글자
- 이름 : 한글 3글자
- 학번 : 숫자 8글자 겹치지않게
## 그 사이에 우리가 무엇을 해주어야 하는가? (로직/DB)
- ID중복체크 #4 
- 학번 중복체크 /user/check_hakbun/20091631 잘되면 200 안되면 400
- DB에 등록을 해주어야하구요.
  - ID
  - PW
  - 이름
  - 학번
  - 최근 로그인 시간(스트링으로 우선 넣읍시다 30글자)
## 사용자가 어떤 정보를 출력 받아야 하는가? (UI/폼)
- 실패했습니다. - 다시 회원가입 페이지를 띄워준다.
- 성공했습니다. - 메인 페이지로 보내준다.

**Comment by juice500ml** [comment]
@juice500 이 책입집니다!

**Comment by juice500ml** [comment]
모든 스트링은 50자

ID: 모든스트링 primary key(중복 불가)

PW: 모든스트링 안전도 체크

First name (KR)
Last name (KR)

EN: 모두 대문자
First name (EN)
Middle name (EN)
Last name (EN)

학번: 숫자 8글자(중복 불가)
최근 로그인 시간

**Comment by minhoryang** [comment]
http://flask.pocoo.org/snippets/54/

**Comment by juice500ml** [comment]
보안에서 이놈을 씁니다!
https://github.com/maxcountryman/flask-bcrypt

**Comment by juice500ml** [comment]
UserDB

username
password_hash
first_name_kr
last_name_kr
first_name_en
middle_name_en (NULLABLE)
last_name_en
student_number (LENGTH 8 INT)
last_login

everything else length 50 string

**Comment by juice500ml** [comment]
+추가기능
admin 인증 후 사용 가능하게. column 하나 더 추가해야함.

**Comment by minhoryang** [comment]
인증이 필요한가요?

**Comment by juice500ml** [comment]
로그인시 기존 인원 다섯명 이상이 OK하면 좋을듯합니당
무분별한 계정생성이 될 듯
- 계정생성에서 봇이 계정을 생성할 수 있지 않을까요?

**Comment by minhoryang** [comment]
무분별한 가입과 봇이 계정을 생성한다면, 
우린 성공한겁니다! HAHA!

**Comment by minhoryang** [comment]
메인 페이지를 만들고 난 다음에, 시작하는게 좋겠네요!

**Comment by juice500ml** [comment]
< 로그인창 >
-누군지 모릅니다.
-누군지 압니다.
-누군지 알고, 가입하면 안됩니다.

세 버튼으로 선택할 수 있게 함.
누군지 압니다 두 명 이상이면 가입 완료
가입하면 안됩니다가 두 명 이상이면 가입 불허
가입이 완료가 안된 경우 모든 로그인한 사람한테 계속 보임.

**Comment by jmg7173** [comment]
누군지 알고 가입하면 안됩니다. 뭔가 나쁘다 ㅋㅋㅋㅋ
넌 가입할 수 없어 이자식아! 이런건가

**Comment by minhoryang** [comment]
무분별한 계정생성 방지는 조금 이따 할까요
