### ISSUE TITLE
CSS 선택자 id와 class 구분 문제

### ISSUE THREAD

**Issue by taeguk** [minhoryang/AwesomeTitle#101]
현재 코드들에서 CSS 선택자중에 id를 써야할 곳에서 class를 쓰는 부분이 많은 것 같습니다.
공통적인 스타일이나 특성을 적용하고 싶은 경우에는 class, 유일한 기능이나 특성을 가지는 경우에는 id 를 사용하는 방향으로 리펙토링을 진행하면 좋을 것 같습니다.

**Comment by minhoryang** [comment]
오오오오오 저도 모르는 부분인데요! 세미나좀요
SGCSRelease/ReleaseWorld#20

**Comment by taeguk** [comment]
@minhoryang 앗!!! ㅋㅋㅋㅋㅋ 근데 저것만 세미나 하기에는 너무 짧구... 세미나를 한다면 '웹 퍼블리싱' 같은 주제로 해야할 텐데 잘 아는 건 아니라서 ㅠㅜ ㅋㅋㅋㅋㅋㅋ 지금 해킹이나 암호 아니면 윈도우시스템프로그래밍 쪽으로 세미나를 해 볼까 생각중이에요.

**Comment by minhoryang** [comment]
조금씩 바꿔주시겠어요?
이 이슈는 클로즈할게요.
