### ISSUE TITLE
신난다~ 로고를 만들었어요~

### ISSUE THREAD

**Issue by juice500ml** [minhoryang/AwesomeTitle#106]
![11](https://cloud.githubusercontent.com/assets/7028312/14227699/71e442d4-f93e-11e5-87a3-55f91d43b0df.png)
[AwesomeTitleLogo.pptx](https://github.com/SGCSRelease/AwesomeTitle/files/200917/AwesomeTitleLogo.pptx)

@SGCSRelease/awesometitle 모두를 소환!

**Comment by minhoryang** [comment]
역시 디자인 자격증 소유자는 다르네요!
테마도 만들어주세요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
부들부들

**Comment by minhoryang** [comment]
이거를 어디에 넣을까요?

**Comment by juice500ml** [comment]
제가 작은 버전을 만들어야할 듯해용 ㅠ

**Comment by juice500ml** [comment]
![1](https://cloud.githubusercontent.com/assets/7028312/14314741/09d53a74-fc34-11e5-81a5-4e618889e119.png)
[AwesomeTitleLogoSmall.pptx](https://github.com/SGCSRelease/AwesomeTitle/files/206275/AwesomeTitleLogoSmall.pptx)

**Comment by minhoryang** [comment]
로고 확정!
