### ISSUE TITLE
본인 계정임에도 내 페이지에서 수정 버튼이 없어요

### ISSUE THREAD

**Issue by p0rygon** [minhoryang/AwesomeTitle#109]
본인 계정임에도 내 페이지에서 수정 버튼이 없어요
내 페이지에 없어야 할 별명 추천란도 있습니다!

**Comment by minhoryang** [comment]
이거 알아볼게요!

**Comment by p0rygon** [comment]
본래 계정 이름이 Ux5인데 ux5, UX5, uX5와 같이 대소문자 구분 없이도 로그인이 되는 문제가 있었습니다.
그렇게 해도 로그인은 되는데 내페이지에서 본인 확인이 안 돼서 [수정]버튼이 안 뜨고 닉네임 추천하는 부분이 뜨는 문제도 있었고요!

db에서 charset이 대소문자 구분 없는걸로 설정되어 있어서 그런 거라고 하시네요. 권한 가지고 계신 분이 charset을 변경해 주셔야 할 것 같습니다.

**Comment by minhoryang** [comment]
역시 사람이 늘어야 버그가 발견되지요!

phpmyadmin 권한 가지고 있는 분들은 한번 로그인해보셔서 user db table에서 UX5를 검색해보고, Ux5를 검색해보세요.
전자는 검색이 안되야하고, 후자는 검색이 되야하는데, 둘 다 검색이 되는 문제가 있었습니다.

이러면 

``` python
found = User.query.filter(
    User.username == USERNAME
).first()
```

에서 둘 다 True로 나오겠죠. Python의 문제는 아니었구요. DB설정자체의 문제였습니다.

![2016-05-07 9 55 27](https://cloud.githubusercontent.com/assets/1270855/15092223/72fc4b32-149e-11e6-9495-fb43efb68f81.png)

phpmyadmin에 user db table를 복제하여 user2 db table를 만들었는데요.
여기에서는 UX5는 검색이 안될겁니다.

![2016-05-07 9 55 18](https://cloud.githubusercontent.com/assets/1270855/15092225/7859bc0e-149e-11e6-80d3-7a6edb9a11f2.png)

차이점은 user table의 username에서 사용하는 데이터 정렬방식을 utf8mb4_unicode_ci 에서 utf8mb4_bin 으로 바꾼 것입니다.

참고) http://stackoverflow.com/questions/21919576/clarification-on-potential-issues-with-equality-of-accented-characters-with-non

**Comment by minhoryang** [comment]
@jmg7173 @juice500ml @SGCSRelease/awesometitle 한번 성지순례오시죠ㄷㄷㄷ

**Comment by juice500ml** [comment]
아닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 와 저런문제가..

**Comment by jmg7173** [comment]
우오... 생각지도 못했는데... 저런문제가(뒷북)
