### ISSUE TITLE
로그인! + Session + 로그인됬는지확인하고Username받아올 수 있는 함수!

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#12]

**Comment by minhoryang** [comment]
https://flask-bcrypt.readthedocs.org/en/latest/

**Comment by minhoryang** [comment]
branch name: issue_12_login

**Comment by minhoryang** [comment]
#1 회원가입기능 작성자 광희 소환! @juice500ml 

Q. 회원가입후에는 자동으로 로그인할 수 있도록 해줄까?

[쿠키저장하고 사용하는 법](http://flask.pocoo.org/docs/0.10/quickstart/#cookies)
하지만 우리는 세션을 이용합시다!
[세션 저장하고 사용하는 법](http://flask.pocoo.org/docs/0.10/quickstart/#sessions)

**Comment by jmg7173** [comment]
일단 로그인하는것만 만들었습니다! (로그인 성공/실패여부)

**Comment by minhoryang** [comment]
와아아아아아아!!!! 나중에 SECRET_KEY는 랜덤생성하게바꾸죠!
os.random()하면될꺼에요!

**Comment by minhoryang** [comment]
이제 할 일은
1. 로그인 URL다듬기
2. URL을 통해 ID를 받는 다른함수들이 있으면, 이걸 get_logged_in_username()이라는 함수를 통해 받아올 수 있도록 해보죠!.

**Comment by minhoryang** [comment]
제가 리뷰했습니다.
잘하셨습니다.
Master브랜치에 머지되었습니다.
짝짝!

**Comment by jmg7173** [comment]
로그아웃이 로그인안해도 작동해요!

**Comment by jmg7173** [comment]
로그인 안한경우에는 버튼이 아예 클릭이 안되도록 바꿔야하고 로그인한 경우에는 버튼이 클릭이 되고 색도 활성화된 버튼이랑 같은 색으로 바뀌어야 합니다.

**Comment by jmg7173** [comment]
수정완료! 커밋만 하면 됩니다.
