### ISSUE TITLE
flake8로 코드의 스타일을 다듬어주세요!

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#13]
``` bash
pip install flake8
flake8 app.py
```

를 쳐서 결과를 보고 수정해주시면 좋겠습니다!

**Comment by minhoryang** [comment]
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by juice500ml** [comment]
09ff6e3d8cfe581b0ca473fc0e29c80c0a1442f4
flake8 added in requirements.

**Comment by jmg7173** [comment]
flake8 적용해서 수정했습니다!
9963177bfce6023891c728db6be0ce1ea334d5ab

**Comment by juice500ml** [comment]
2f97716835872973992b27163931c90906b765a4
added in DEVELOPMENT.md
