### ISSUE TITLE
README.md와 DEVELOPMENT.md를 가꿉시다.

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#17]

**Comment by minhoryang** [comment]
#13 DEVELOPMENT.md 에 flake8 을 사용하는 법도 올려주세욧!
#15 manage.py가 db.py로 바뀌었다고 DEVELOPMENT.md 를 수정해주세욧!
@juice500ml

**Comment by juice500ml** [comment]
#15 done! 3f4333f3339987b604f9a9c0ff399518a895e4ce

**Comment by juice500ml** [comment]
#13 done! 2f97716835872973992b27163931c90906b765a4

**Comment by minhoryang** [comment]
ROADMAP.md도 있어요!
