### ISSUE TITLE
매 주 추천총량 1등만 누가 누구에게 닉네임을 추가했는지 알 수 있게!

### ISSUE THREAD

**Issue by jmg7173** [minhoryang/AwesomeTitle#19]
싸움나는것좀보죠. -minhoryang

**Comment by juice500ml** [comment]
추가기능: 매 주 추천총량 1등만 누가 누구에게 닉네임을 추가했는지 알 수 있게!

**Comment by juice500ml** [comment]
*그 전 주 추천총량(다른 사람한테 별명을 추천해준 수)이 최대였던 user이 해당 주에 누가 추천을 받고 했는지 알 수 있도록 하면 좋을 것 같아요

**Comment by minhoryang** [comment]
최대 지분소유자?
최대주주?

**Comment by juice500ml** [comment]
추천총량 = (그 전주에 추천 총 갯수) + (그 전주에 추천이 받아들여진 갯수)*(임의 상수 N)
