### ISSUE TITLE
README.md와 달리, 항상 URL에 추가하지 말고 사용자가 선택할 수 있게합시다!

### ISSUE THREAD

**Issue by jmg7173** [minhoryang/AwesomeTitle#20]
README.md와 달리, 항상 URL에 추가하지 말고 사용자가 선택할 수 있게합시다!

왜냐면
- 이름도 겹치고
- 닉네임도 겹칠 수 있기 때문입니다.

**Comment by minhoryang** [comment]
- 이름이 겹치면 검색기능으로 보냅시다!
- 닉네임이 겹치면 어떻게 할까요? 검색기능이 있으면 URL에 추가하는걸 항상 물어볼 필요가 있나요?

**Comment by jmg7173** [comment]
- 별명으로 자기페이지를 들어가면 URL을 바꾸지 않습니다.
  - URL을 바꾸지 않는다면 자기 페이지에서 어떤 동작을 수행했을때 내부에서는 username으로 작동되고 외부에 URL등으로 보여줄때는 별명으로 보여주도록 하면 될까요?
    - (minhoryang) 그렇게 해야 redirect(goto())에 비하여 DB를 확인하는 과정이 줄어들거에요.
      - (jmg7173) 그렇다면 페이지를 보여주는 함수에는 항상 User.username을 저장하는 변수가 있어야 겠군요

**Comment by minhoryang** [comment]
@jmg7173 와의 회의록입니다.
- 내가 나인걸 굳이 URL DB에 (minhoryang, minhoryang)으로 등록하여야 하나?
  - 이거 이미 User DB에 있잖아요. 검색 2번 하죠?
    - (jmg7173) 검색을 2번 하면 느려지지 않나요?
      - len(User) <<<<< len(URL) <<<<< len(별명) 아닐까요?
        - (jmg7173) 오오

**Comment by minhoryang** [comment]
- 현재 우리 URL DB구조는 Link(primary), Username 이렇게 구성되어있다.
- 내 이름이 다른 사람의 닉네임과 겹치면 어떻게 해야하나? 
  - 닉네임이 먼저 등록되면 뺏나?
  - 이름이 먼저 등록되면 닉네임을 등록 못하나?
- 내 이름이 다른사람의 이름과 겹치면 어떻게 하나?
- 내 닉네임이 다른 사람의 닉네임과 겹치면 어떻게 하나?
- 검색기능은 나중에라도 도입한다고 할 때, 위 중 어느 고민에 검색기능을 제공해주어야하나.
- (jmg7173)이름이 username인가요 아니면 실명인가요? 실명이겠죠..?

**Comment by jmg7173** [comment]
- 중복허용할 경우
  - 링크에서 어떤 사람 페이지를 보여주려 할때 User DB에서 검색 + Nickname DB에서 검색으로 결과를 모아 페이지를 선택할 수 있도록 한다.
    - 단, 결과가 하나인 경우 바로 보여준다.
    - 보여줄 수 있는 페이지를 선택 하라고 할 때 {ID : 별명/ID, ...}와 같이 구성된 자료구조를 만들어주고 그 중에 선택된 ID를 넘겨주고 URL은 변화하지 않는다.
      - 그렇다면 하이퍼링크처럼 페이지를 연결해 줄 수 있는 어떤 것의 선택창은 별명/ID(ID)로 보여줍니다.
- 중복허용안할 경우
  - 위의 문제들이 발생한다.
  - 나중에라도 DB를 바꿔 중복허용한다고 가정했을때(idx를 primary로 하고)
    - 지금 당장은 링크넘겨줄 때 username을 기본값으로 링크넘겨줄 때 DB중 User에서 먼저 찾고 없으면 Nickname DB에서 찾는다.
      - 그러면 먼저 닉네임을 등록했는데 나중에 회원가입한 사람이 링크를 빼앗게 됩니다.
      - 그렇다면 실명이 다른사람의 nickname이나 username과 겹친다면?
        - 실명도 홈페이지 링크에 쓸지 말지는 nickname과 같이 정했으면 좋겠습니다! 그러면 문제해결! 아.. 아닌가
    - 지금 DB구조는 Link가 primary니까 어떤사람이 이미 닉네임을 선점한경우 다른사람이 같은 닉네임을 링크로 하려고 해도 막히겠죠
  - 음.. 검색기능은 어디에 제공해줘야할지 모르겠어요. 그냥 다 제공해줄까요? 그럼 너무 느려지나..
  - +) 근데 기본값으로 실명(영어포함)으로 링크 입력해도 들어갈 수 있게 해야하나요?

**Comment by juice500ml** [comment]
- 몇몇 정해진 링크(register, login, 등)에만 중복허용 금지, 나머지는 허용하는건 어떤가요?
  - 이건 링크에 안쓰기로 했지롱!(jmg7173)

**Comment by minhoryang** [comment]
몇몇 정해진 링크는 싸우면 걔네가 이깁니다 훗ㅋ

**Comment by minhoryang** [comment]
README에 부족한 점이 무엇이 있을까요?
- 쓰면 좋다는걸 좀 더 표현해줬으면 좋겠어요.
- 세부 컨셉이 부족하고, 조금 바뀐게 있어요.
  - 이슈를 들어가보면서, 바뀐 점을 보여줬으면 좋겠네요.
- 로고도 필요해요
  - 없으니까 스크린샷이라도 올릴까요?
- 우리가 구현한 기능들만 나열하고 싶어요.
  - /api같은건 빼구요
  - 소그룹 업적 아직 안만들었구요.
  - 이메일도
  - 휴대폰도
  - 닉네임을 추천하는 과정이나 자신이 선택하는 부분에 대한 설명이 부족해요.
- 매 기능을 추가할 때마다 README도 같이 수정했으면 좋겠어요.
- 이슈에 링크를 다 걸어주셨으면 좋겠어요. 아니면 번호라도!
- 질문이 중간중간 들어가있어서 한눈에 보기 힘들어요. QUESTIONS.md를 만들고 각각을 이슈로 만들어서 링크할까요?
- 언제든지 후배들이 개발에 뛰어들 수 있었으면 좋겠어요. 그럴려면 개발가이드가 링크가 되어있으면 좋겠네요.
