### ISSUE TITLE
가입할때마다 이름을 저렇게나 많이 입력해야하나요?

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#21]

**Comment by juice500ml** [comment]
국제화시대에 발맞춘 영어이름!

**Comment by minhoryang** [comment]
Where is my middle name!

**Comment by JimJeon** [comment]
Last Name(KO)는 이름이 아니라 family name이 들어가도록 해야할 것 같습니다

**Comment by jmg7173** [comment]
한글이름에는 Last와 First 구분을 빼버리면 어떨까요? 탭하기 귀찮아요

**Comment by juice500ml** [comment]
아예 이름을 단 하나만 받아버리는것도 방법인듯합니당

**Comment by minhoryang** [comment]
##오늘의 회의 결과
- 풀네임으로 하나만 받을 것
- 이름 관리 페이지 없애기

## 구현순서
- 기존의 이름을 지우기 전에,
- 풀네임으로 보관할 새 Column을 넣어줌
- 함수를 잘 짜서, 기존의 이름을 새 풀네임으로 잘 변환
- /admin페이지에서 확인
- 기존의 이름을 지움.

**Comment by minhoryang** [comment]
어. Structure Migration은 쉽지만 (flask-migrate(alembic)의 migrations폴더 참고)
Data Migration은 어렵죠.
이걸 똑같이 migration/versions 폴더에서 관리하고 싶나용? 두개의 기능을 한 파일에 넣는것은 매우 위험해 보입니다.
그러니까 특정한 폴더를 하나 더 만든다음에, 현재 DB의 버전이 우리가 원하는 버전이 맞는지 확인하고, 진행해주는 스크립트를 보관하면 좋겠습니다!

**Comment by minhoryang** [comment]
역방향만 포기하면 될 것도 같은뎁?!

**Comment by minhoryang** [comment]
음 migration/versions에서 우리의 db.py에 접근하는걸 시도해보고, 아마 이게 안되면 Package로 만들지 않아서 생기는 문제 일건데, 그러면 중간만 따로 함수를 만들거나 URL같은걸 임시로 만드는 방향으로 생각해줘.
너무 오래 잡지 말자구!

**Comment by juice500ml** [comment]
commit d9d31474ac03700a06838194d04a839bd3bb7548
commit 98cc1c2f40a87958499d262921bd3b63a38ed5c7
done!

**Comment by minhoryang** [comment]
디비 마이그레이션은 98cc1c2f40a87958499d262921bd3b63a38ed5c7
실제 서버 코드는 fe8e708a3ecc5189a82e723e451dbc86b13be305
에서 하셨네요 굳굳!
