### ISSUE TITLE
별명을 추천하고 관리하는 페이지가 없어요. 

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#33]
사실 기능은 있는데,

내 프로필이 아닌, 다른 사람 프로필을 보면, 바닥에 별명을 추천할 수 있도록 해주었으면 좋겠어요.

**Comment by minhoryang** [comment]
추천하는건 제가
관리하는건 @jmg7173 가 하고잇어요.

**Comment by minhoryang** [comment]
추천하는거 끝!
8878add87d612e3437893e6353136e445c3b0c70

**Comment by jmg7173** [comment]
완료했지만 소소한 버그가 있습니다!
