### ISSUE TITLE
정사각형 사진이 아니면, 프로필 사진이 짜부돼요. ㅠㅠ

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#35]
근데 어렵습니다. ;ㅅ;

**Comment by minhoryang** [comment]
업로드 페이지에 경고 문구를 넣어두었어요.

**Comment by juice500ml** [comment]
quick (and dirty) fix for image cropping 7b1a1603be21745b2309ca35df689a174bc66714
(branch issue_35)

**Comment by minhoryang** [comment]
오오오오!
<image src="">가 아니라
<image style="background-image:url(''); background-position-*:center">으로 하면, CSS로 가운데 정렬을 구현할 수 있대요!
의외로 쉽게 해결했네요! SOLVED!
