### ISSUE TITLE
에러메세지가 UI 안에서 나오는게 아니라 쌩으로 나와서 메뉴등을 통해 다시 돌아올 수 없어요.

### ISSUE THREAD

**Issue by jmg7173** [minhoryang/AwesomeTitle#39]
에러메세지가 뜨면 기본 폼이 사라져서 기본페이지로 돌아오려면 주소를 다시입력해야해요! 
불편합니다.

**Comment by jmg7173** [comment]
에러메세지 뿜을때 화면을 따로 .html로 빼야하는걸까요 같은 .html파일 내에서는 처리 못하나요?

**Comment by minhoryang** [comment]
지금 main.html의 naeyoung에 넘겨주면 되지 않나용!

**Comment by jmg7173** [comment]
오호 그렇게 하면 되는군요! 그럼 이건 템플릿 정리 후에 수정하도록 하겠습니다.

**Comment by minhoryang** [comment]
#41 에서 해버렸습니다!

**Comment by jmg7173** [comment]
확인된 에러창 : 회원가입시의 에러

아직 안된 에러창 : 로그인
- 404페이지를 제외(제외하지 말까요...) 모든 에러창을 출력 후 1초후 원래 창으로 복귀하는것을 넣었으면 좋겠어요

**Comment by minhoryang** [comment]
아니요! 그럼 그렇게 만들어보시겠어요? +_+

**Comment by minhoryang** [comment]
리다이렉션 관련은 따로 버그를 만들어 주세욧!
