### ISSUE TITLE
템플릿 구조를 다시 짭시다!

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#41]
# 기존 Template 구조의 문제
- Template에 넘겨주는 변수명이 뒤죽박죽이라서, 이 변수가 무슨 값을 가지는지 알기 쉽지 않음.
- 같은 변수 값이면, 여러 template에서 공용으로 사용함. (다 쪼개야함)
- Template의 상속구조가 복잡
- 실제 render_template()에 넘겨주는 Template A와 그 A가  상속받거나 사용한 Template B가 무엇인지 알기 힘듬.
# Jinja2에서 지원하는 몇가지 테크닉들
## 사용했던 테크닉
- 블럭 `{% block NAME %} ... {% endblock %}`
  - 들어갈 공간을 선언해 놓고, 사용하지 않아도 됩니다.
- 상속 `{% extends %}` 을 통한 블럭 사용
- 삽입 `{% include "_profile.html" %}`
## 되는지는 모르는데 사용하고픈 테크닉
- `{% include VARIABLE %}`
- ...
# 새 레이아웃의 방향
## 재사용 가능한 규칙적인 상속 구조 설계

![사진](http://f.cl.ly/items/472J1N0r3i1q1a1x2n0c/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202016-03-01%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%2011.18.55.png)

**Comment by minhoryang** [comment]
@juice500ml @jmg7173 어떻게 생각하세용.

**Comment by minhoryang** [comment]
사진도 추가해 보았습니다.

**Comment by juice500ml** [comment]
pages/__blank.html가 필요한가 싶습니당~

**Comment by jmg7173** [comment]
profile.html과 blocks/profile.html의 차이를 모르겠습니다! 사진에 없어서 그런건가..
blocks/~.html파일과 ~.html파일은 같은건가요?

**Comment by jmg7173** [comment]
사진으로 설명된 부분은 잘 이해됐습니닷

**Comment by minhoryang** [comment]
@juice500ml 사실 안필요한데 혹시나 나중에 404페이지나 이런거 필요할까봐

**Comment by minhoryang** [comment]
@jmg7173 blocks/profile.html과 profile.html은 다른거에요.
Profile.html은 _main을 상속받아서 blocks/profile.html을 가지는거죠.

**Comment by minhoryang** [comment]
사진의 index.html이 profile.html이네요.

**Comment by minhoryang** [comment]
#21 도 묶여있음 (#48)

**Comment by minhoryang** [comment]
[비포 애프터를 보고싶으시면 여기로!](https://github.com/minhoryang/AwesomeTitle/compare/cfd1fa5311055b5c619d974ce46271af0571374e...dd13fbb0fb97e380b5b08b2aa29e9767a21cec0e)

**Comment by juice500ml** [comment]
우와ㅏ아아ㅏ아아아ㅏ아ㅏ아아ㅏ아ㅏㅏㅏㅏㅏㅏ 수고하셧습니다ㅏ아아ㅏㅇ아!!

**Comment by jmg7173** [comment]
헐헐 밤사이에 무슨일이 ㄷㄷㄷㄷ 수고하셨습니다ㅏ아ㅏㅏㅠㅠ
