### ISSUE TITLE
회원 탈퇴기능

### ISSUE THREAD

**Issue by jmg7173** [minhoryang/AwesomeTitle#44]
누가 릴리즈에서 나가고 싶나봐요! ㄷㄷ (저는 아닙니다)

**Comment by JimJeon** [comment]
해.. 해보자!...( 할 수 있을까 )

**Comment by minhoryang** [comment]
모든 DB를 돌면서
자신이 포함되어 있는 것을 지우고 나가면 되겠죠!

**Comment by jmg7173** [comment]
엇 어렵나요 히이익

**Comment by minhoryang** [comment]
쉽고도 어렵죠!

**Comment by minhoryang** [comment]
근데 쉽습니다.

**Comment by jmg7173** [comment]
오 현답인 것 같아요!

**Comment by JimJeon** [comment]
T^T 맡아서 완성시켜보겠슴다

**Comment by minhoryang** [comment]
관리자 페이지 맨 밑에
메뉴로 추가해줘요!

**Comment by minhoryang** [comment]
오 굳굳!

**Comment by JimJeon** [comment]
기능구현 했습니다.

추가로 구현해야 할 것들...
1. 탈퇴하시겠습니까? (y/n) - 알림창
2. 탈퇴되었습니다. - 확인 페이지 혹은 알림창
3. 탈퇴사유 설문조사?

**Comment by jmg7173** [comment]
User DB뿐만 아니라 다른 DB에서도 탈퇴하는 회원의 정보를 삭제해야합니다!

**Comment by jmg7173** [comment]
@JimJeon 어서 일해라!

**Comment by minhoryang** [comment]
찰싹찰싹

**Comment by juice500ml** [comment]
어려워요..

**Comment by JimJeon** [comment]
드디어 기능 구현 끝났습니다!!

**Comment by JimJeon** [comment]
추가적으로 구현하고 싶은 기능은 새 이슈로 만들까요?

**Comment by minhoryang** [comment]
@JimJeon 네! 그리고 연결해주세요!

**Comment by minhoryang** [comment]
지금 리뷰가 #60에서 진행되고 있는데요.
여기에 있는 리뷰를 참고해주세요.
그리고 엄청 잘하셨어요.
특히 로그아웃! 신경써주신거 최고.

그리고 크리티컬 이슈가 있는게.
http://title.reluv.me/anyone/manage/withdrawal/ 로 들어간 로그인 된 유저는 바로 탈퇴가 되는 이슈가 있는데요.

쉬운 해결책은,
1. 중간단계로 진짜 탈퇴할지를 물어보는 페이지를 만든다
2. 그리고 실제 탈퇴를 진행하는 페이지는 POST로만 받도록 한다.
면 될 것 같아요.

POST요청은 꼭 form을 submit해야지만 진행 된다고 생각할 수 있거든요.

아니면 탈퇴 예약같은걸로 바꾸는거에요?
그래서 다음날 0시에 지워주겠다고 하면
취소할 수 있겠죠?

두분의 생각도 들어보고 싶네요. @jmg7173 @juice500ml

**Comment by JimJeon** [comment]
감사합니다!!!

말씀하신 if link != username: return ' ', 400 구문은 추가했습니다.
사실 진짜 탈퇴하시겠습니까? 라는 페이지가 뜨게 하고싶은데... 방법을 모르겠어요... ㅠㅠ
이거 하려면 withdrawal.html이라는 파일에 <SUBMIT> 태그를 이용하면 되는건가요?

탈퇴 예약 기능! 너무 좋은거 같아요!! 전 이 방법으로 되게하고 싶습니다!

**Comment by yunitto** [comment]
탈퇴 예약기능은 관리자가 탈퇴처리를 해주는건가요? 그럼 관리자가 너무 번거롭지 않을까요.. 저는 중간에 진짜 탈퇴하시겠습니까? 단계를 더 넣어주는게 더 나을거같아욤

**Comment by minhoryang** [comment]
- 탈퇴 예약 기능은 추가기능으로 하구요. (Celery라는 비동기 큐 기능이 필요해서 그래요)
- 진짜 탈퇴하시겠습니까? 라는 페이지가 뜨려면!
  1. 기존에 만들어놓은 함수의 이름을 바꾸고, 새 URL을 준 후,
  2. 기존 함수의 이름을 본 딴 함수를 만든다.
  3. 기존 함수의 리턴이 render_template("withdrawal.html") 으로 해주면, withdrawal.html이 그려져요
  4. withdrawal.html 안에 진짜 탈퇴하시겠습니까? 라는 체크박스를 넣고
  5. 그리고 form에서 submit버튼을 누르면 새 URL로 POST로 가게 해주면 되요 (login.html을 확인해보세요) 
  6. 이건 @juice500ml (디자인자격증 필기 합격) 이가 잘 도와주실거에요.

**Comment by minhoryang** [comment]
앗 유니또에게 잔다고했는데;ㅅ;;

**Comment by JimJeon** [comment]
@yunitto 
트위터 탈퇴기능처럼 일정 기간이 지나면 자동으로 탈퇴되게 하면 될거 같아요!
중간에 정말 탈퇴하시겠습니다란 페이지를 지나도 바로 탈퇴가 되지는 않는거예요.
사람 마음은 갈대,.. 번복할 수 있는 기회를 주는거죠

**Comment by JimJeon** [comment]
라고 생각해봣어요

**Comment by yunitto** [comment]
코멘트 안 달면 계속 생각나서 밤새 못 주무실테니 용서해드릴게요(찡긋)

**Comment by minhoryang** [comment]
@JimJeon 트위터계정불러
@yunitto (찡긋)

**Comment by juice500ml** [comment]
@JimJeon 에 동의!

**Comment by JimJeon** [comment]
@minhoryang 헉.. 저 트위터는 지워버렸어요 ㅠ 그래서 탈퇴기능을 알고있지요 :)

**Comment by minhoryang** [comment]
메인 컨트리뷰터 다 모였네욬ㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
@JimJeon 잘도망가네^^

**Comment by JimJeon** [comment]
@minhoryang 헉;

**Comment by juice500ml** [comment]
AngryOnJim...

**Comment by JimJeon** [comment]
지.. 지금 만들겟습니당

**Comment by yunitto** [comment]
@JimJeon 오 자동탈퇴라면 좋을거같아요!!

**Comment by minhoryang** [comment]
나중에 Celery를 도입하면, 그날 저녁에, 원하는 함수를 호출하게할 수 있을거에요.
(그러니 이부분은 나중으로!)

**Comment by minhoryang** [comment]
성지순례왔습니다!!!!!! 대박잘했어!!!!

**Comment by juice500ml** [comment]
:+1:
