### ISSUE TITLE
빈 이미지 업로드 가능

### ISSUE THREAD

**Issue by juice500ml** [minhoryang/AwesomeTitle#46]
![2016-03-02 2 56 49](https://cloud.githubusercontent.com/assets/7028312/13451975/04cc4bd0-e087-11e5-9523-724be0678578.png)
파일 없이 Submit 버튼 누를 경우 빈 이미지로 됨.

![2016-03-02 2 56 55](https://cloud.githubusercontent.com/assets/7028312/13451974/04c94142-e087-11e5-9653-d1933b9c15a9.png)

**Comment by jmg7173** [comment]
히이이이익

**Comment by jmg7173** [comment]
@JimJeon 해볼래?

**Comment by JimJeon** [comment]
맡

**Comment by minhoryang** [comment]
올ㅋㅋㅋㅋㅋㅋㅋㅌㅌㅌㅌ

**Comment by juice500ml** [comment]
fixed
commit 3687b09c0d76af72373cbbee3c0d5918e266014b

@JimJeon 
![maxresdefault](https://cloud.githubusercontent.com/assets/7028312/13455212/3964f8de-e09f-11e5-8445-928d1b223b8a.jpg)

**Comment by minhoryang** [comment]
진짜 이걸로 검출이 되나옄ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
