### ISSUE TITLE
회원가입할 때 아이디를 쓰면 "써도 좋습니다." 알림이 뜨는거 불편해요

### ISSUE THREAD

**Issue by jmg7173** [minhoryang/AwesomeTitle#48]
대신 옆에 Success!(초록/연두) Failed!(빨강)를 출력해줬으면 좋겠어요.
게다가 알림떴을때 엔터라도 치면.. 회원가입이 시작돼버려요 그래서 회원가입 에러를 띄워주죠 난 알림에 대해 엔터를 쳤을뿐인데! ㅂㄷㅂㄷ( @yunitto )

**Comment by minhoryang** [comment]
Zzzzzzzxxzx

**Comment by juice500ml** [comment]
Issue #41 에서 정해지면 다시 짤듯합니당!

**Comment by minhoryang** [comment]
예쁜 Form:
http://v4-alpha.getbootstrap.com/components/forms/
팝오버를 통한 알림:
http://v4-alpha.getbootstrap.com/components/popovers/#example-enable-popovers-everywhere

**Comment by minhoryang** [comment]
@juice500ml 코멘트좀 부탁해요~~

**Comment by juice500ml** [comment]
학교가서 놋북으로 하겟슴당~

**Comment by minhoryang** [comment]
@juice500ml 주석보다는 그냥 여기에 어떤거어떤걸 이용해서 만들었다~ 정도만 기록으로!

**Comment by juice500ml** [comment]
부트스트랩 기초 사용법!
https://github.com/minhoryang/AwesomeTitle/wiki/부트스트랩-기초-사용법

**Comment by minhoryang** [comment]
@juice500ml 감사합니다 +1
