### ISSUE TITLE
프로필 사진을 아예 지워서 기본사진으로 바꿔주세요! (카톡도 그렇잖아요!)

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#49]
#46 "빈이미지 업로드 가능"은 버그였구요.

**Comment by juice500ml** [comment]
방금 만들었어요! https://romannurik.github.io/AndroidAssetStudio/
![ic_launcher](https://cloud.githubusercontent.com/assets/7028312/13459043/465d2bb4-e0b4-11e5-8db5-070053adccca.png)

**Comment by yunitto** [comment]
프로필사진 삭제 기능 아직 안만들었어요

**Comment by minhoryang** [comment]
네~

**Comment by juice500ml** [comment]
일해라! @yunitto !

**Comment by minhoryang** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by juice500ml** [comment]
관리 페이지에서 이미지를 클릭하면 프로필 이미지 삭제를 할 수 있도록 질의를 띄워줘도 좋을 듯!

**Comment by minhoryang** [comment]
이게 프로필용 이미지 보기 및 관리 페이지와
실제 관리 기능을 수행하는 페이지로 나누기로 이야기를 했습니다. - to @juice500ml

**Comment by juice500ml** [comment]
넹!

**Comment by minhoryang** [comment]
제가 코드리뷰를 해봤어요!
이거 적용하고, 잘 되는지 확인하시고, 커밋 주시면, @jmg7173 가 머지할거에요!
https://github.com/minhoryang/AwesomeTitle/commit/2d98d583b860446d213cccabf2b8ee16d4f541b3#diff-d186e2f66660a64ffe222c34651aee9aR104

**Comment by minhoryang** [comment]
https://github.com/minhoryang/AwesomeTitle/pull/59

**Comment by minhoryang** [comment]
머지되었습니다! 짝짝짝!!!!
