### ISSUE TITLE
URL DB들은 다 같은 페이지를 보여줄 겁니다. 어떻게?

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#5]

**Comment by minhoryang** [comment]
디비 설계를 어떻게 해야 될까요?

**Comment by minhoryang** [comment]
````python
class URL(db.Model):
    from: [특정 USER이름]
    to: 지정하고픈 이름들 (별명/번호/....)
````

**Comment by juice500ml** [comment]
지정하고픈 이름들을 primary key로!

**Comment by jmg7173** [comment]
학번을 primary key로?!

**Comment by minhoryang** [comment]
```python
@app.route("/<id>")
def goto(id):
    return id + "의 페이지 입니다."

@app.route("/register")
def register():
    return '회원가입용 페이지 입니다.'
```

우리는 모든 ID를 다 제공해 주고 싶은데.
특정 URL(예를 들면 회원가입) 같은거는 우리가 이미 차지하고 있음.
그래서 그 URL을 생성할 수 있는지 확인하는 함수가 필요함.

**Comment by minhoryang** [comment]
휴대폰DB나 별명DB에서 직접 URL을 추가해 달라고 요청할 것임.
그 요청을 처리하는 함수도 있어야함.
addURL("양민호", "minhoryang") --> DB에 추가해주는거지
isAbleToAddURL("양민호") -> true/false

**Comment by jmg7173** [comment]
link를 primary key로 놓고 ID와 매칭시켜서 어떤 아이디가 여러 URL을 생성시켜 들어가면 하나의 페이지로 가도록 완성했습니다.

**Comment by minhoryang** [comment]
@jmg7173 가 4710179b83a2d5e8fd22c9f6207e40630dde45f4 에 작업해서 올렸습니다!
수고했습니다!!!!!

**Comment by jmg7173** [comment]
아이디 체크 기능 추가했습니다.
