### ISSUE TITLE
회원가입때 학번 필터링 해주셔야죠?

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#52]

**Comment by jmg7173** [comment]
(대학원생 학번은 기입안한다는 전제하에) 앞의 4자리를 끊어서 1960과 현재년도 사이에 있는지 확인하고 뒤의 네자리가 유효한 범위(약 2000쯤 되지 않을까요)에 있는지 확인하고 DB에서 겹치는 학번이 없는지도 확인하면 될듯합니다. @JimJeon 이나 @yunitto 일감이 생겼다! 어서 일해라!

**Comment by yunitto** [comment]
제가 할게영~

**Comment by minhoryang** [comment]
되었습니다!!!!!!!! 와아아아아아아!!!!!!!!!!!
