### ISSUE TITLE
자기별명 관리 DB

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#7]

**Comment by JimJeon** [comment]
디비디비 딥!

**Comment by JimJeon** [comment]
Index / ID / Nickname

**Comment by JimJeon** [comment]
본명 / 추천 DB와 연결

**Comment by JimJeon** [comment]
primary key는 idx를 이용한다.

아이디 / 별명 / 추천인 /

매 idx마다 본명을 추가하면 데이터 낭비?
아이디를 이용해서 별명의 주인을 찾자!

**Comment by JimJeon** [comment]
class Nickname:

> idx
> usr
> nick
> suggest

**Comment by JimJeon** [comment]
Q. 겹치는 별명을 허용해야 할까요?
@minhoryang @tmdghks0612

**Comment by JimJeon** [comment]
##별명 관리 페이지

자신의 별명 관리 페이지를 만들기 시작했습니다.

Q. 로그인한 본인만 관리를 해야겠죠? 그렇다면 로그인 정보를 어디서 가져와야 할까요? -> 만들었습니다!!

 --- > 우선은 /nickname/<user>/ url을 이용해서 작업하겠습니다.
1. 별명 추천 DB를 불러와서 자신이 추천 받은 것들을 리스트로 보여줘야겠죠?
2. 자신의 별명 탭, 추천받은 별명 탭이 있었으면 좋겠습니다.
3. 자신의 별명 탭에는 별명 추가, 별명 삭제, 별명 수정 기능이 있어야 하겠죠?
   
      ---- > 아니면 자신은 별명을 추가하지 못하게 해서 추천받은 별명만을 등록할 수 있게 할까요?
4. 추천받은 별명 탭에는 자신의 별명으로 추가, 추천 삭제 기능을 넣어야 할 거 같습니다.
5. 추천한 사람 추천하기 기능을 넣어볼까요?

**Comment by minhoryang** [comment]
@JimJeon 으아아아아아아앙 어떻게됬나요!!! OT는 재밋었나요!!!!!!!!!

**Comment by jmg7173** [comment]
짐전 曰 : 별로 안해서 새로해도 돼요
바톤 터치했어요

**Comment by jmg7173** [comment]
Issue 이름을 자기별명 관리 DB로 바꿨으면 좋겠어요!

**Comment by minhoryang** [comment]
네! 바꾸세요!!
