### ISSUE TITLE
별명이 빈칸이어도 추천이 됩니다.

### ISSUE THREAD

**Issue by JimJeon** [minhoryang/AwesomeTitle#71]
![screenshot from 2016-03-05 12-17-18](https://cloud.githubusercontent.com/assets/16199830/13545367/60788f9c-e2cc-11e5-9f6b-03ddb13e954b.png)

이 무슨 일이란 말인가!

**Comment by minhoryang** [comment]
[책임자를 가려냅시다](https://github.com/minhoryang/AwesomeTitle/blame/master/nickname.py)

**Comment by jmg7173** [comment]
@JimJeon 가라 짐전! 문자열 길이만 비교하면 된다! 50글자 넘어가는지 체크도 해주고

**Comment by JimJeon** [comment]
출동!

**Comment by JimJeon** [comment]
0글자이면 추천이 안되게했습니다.
1. 에러메세지 띄우고 다시 전 페이지로 돌아가는거도 추가하고 싶어요!
2. 에러메세지 내용 추천 받습니다.
3. 50글자 넘어가는것은 이미 칸에 쓸 수 없게 막아져 있더군요!

**Comment by juice500ml** [comment]
@JimJeon 에러메세지 띄우는 건 별개의 이슈로 만들어주세용 이 이슈는 닫습니다!

**Comment by JimJeon** [comment]
넵! 그나저나 close되었다는건 pull 해서 merge 해도 된다는건가용

**Comment by minhoryang** [comment]
네! 당연하죠!
