### ISSUE TITLE
프로필 페이지에 달성한 업적을 보여주고 싶어요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#72]
1.**사용자가 직접 선택한 마이 프레셔스 업적 5개**를 먼저 보여줘요
그 다음부터는 조건을 선택해서 원하는 순서대로 나열할 수 있어요
- 예시) 업적 달성한 순서, 레어한 순서 등  

2.**시도중인 업적**을 보여줘요
- 승인 대기중인 업적
- 진행중인 업적 (%)  

3.**달성하고싶은 업적**도 보여줄게요

**Comment by minhoryang** [comment]
### 충분조건

DB가 있으면 좋죠.
그런데 디자인 하는데는 DB가 필요하진 않아요.
DB랑 구성요소만 맞춰주시면 되요.
- #78 <신청식> 업적 DB
- #79 <자동 달성식> 업적 DB
- #80 <수동 승인식> 업적 DB

### 필수조건:
- #77 업적소개DB
- (새 이슈 필요?) 마이프레셔스를 저장할 업적 DB가 필요해요
- (새 이슈 필요?) 달성하고싶은 업적을 저장할 DB가 필요해요
- (새 이슈 필요?) 레어도를 판단하는 기준이 필요해요

### Q. <달성된> 업적 DB가 추가적으로 있다면 어떨까요? 훨신 수월해지지 않을까요?

**Comment by minhoryang** [comment]
#77 업적소개 DB가 끝나면, 바로 시작하셔도 되요.
