### ISSUE TITLE
업적 리스트 페이지와 연결되는 각 업적별 세부소개 페이지가 필요해요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#74]
1.**각 업적 기본 설명**
- 이름
- 로고
- 짧은 설명
  - 어떻게 달성 가능한지?

2.**진척 상황**

3.**업적별 인원 수와 비율**
- 업적을 달성한 사람
- 시도중인 사람
- 위시리스트에 있는 사람?

4.**만들어진 시간**

5.**해당 업적을 만든 사람**

6.**관리자 버튼**

**Comment by minhoryang** [comment]
#77 업적소개 DB가 끝나면, 바로 시작하셔도 되요.
