### ISSUE TITLE
개인별 업적관리 페이지가 필요합니다!

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#75]
1.자기 프로필 페이지에서 보여주고 싶은 **마이 프레셔스 업적 5개**를 선택할 수 있어야해요!!

2.**<수동 승인식>** 승인 대기중인 업적을 취소하는 기능도 필요해요

**Comment by minhoryang** [comment]
#80 <수동 승인식> DB의 개발이 끝나면, 바로 시작하셔도 되요.
