### ISSUE TITLE
업적 생성자용 관리 페이지가 필요해요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#76]
**1.이름/로고/설명**을 수정하는 기능  

**2.업적 달성조건** 기입

**3.**<수동 승인식>인 경우 승인 요청자를 확인하고 승인할 수 있어야해요

**4.업적 소유자 리스트**를 보여주고 싶어요

**Comment by yunitto** [comment]
Q. 업적 관리페이지는 업적을 만든 사람이 관리하나요? 아님 홈페이지 전체 관리자가 하나요?
A. @minhoryang: 업적을 만든 사람이 관리합니다.

**Comment by yunitto** [comment]
업적 달성 조건은 수정할 수 없게 만들어야 합니다.

**Comment by minhoryang** [comment]
#80 <수동 승인식> DB의 개발이 끝나면, 바로 시작하셔도 되요.
