### ISSUE TITLE
휴대폰 DB

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#8]

**Comment by yunitto** [comment]
1빠ㅏㅏㅏㅏㅏ

**Comment by minhoryang** [comment]
휴대폰 DB에 필요한게 뭐가 있을까요?

**Comment by minhoryang** [comment]
휴대폰번호
해당 사람 ID
폰 종류?
카톡사용여부
밴드사용여부
카톡아이디
라인아이디

휴대폰 번호 중복 체크!

**Comment by yunitto** [comment]
primary key 는 idx가 됨

**Comment by minhoryang** [comment]
휴대폰 번호가 없을 수도 있음.

**Comment by minhoryang** [comment]
카톡사용여부
밴드사용여부
카톡아이디
라인아이디
이건 나중에 합시다!

**Comment by yunitto** [comment]
같은 번호는 다시 추가할 수 없음

**Comment by minhoryang** [comment]
@yunitto 유니또오오오오오오오오오!!!!!!!!
