### ISSUE TITLE
<자동 달성식> 업적의 서버 프로그램

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#81]

**Comment by minhoryang** [comment]
### 충분조건
- #79 <자동 달성식> 업적 DB : 환경을 구축하는게 먼저, 서버를 짜는건 그 다음. DB는 아래 Script에서 쓸 것.
- <자동 달성식> 업적들을 celery task로 만든 python 스크립트 (쉬운이슈)
- #82 외부계정DB : 위의 Script에서 쓸 것이기 때문에, 나중에 도입해도 됨.

### 필요조건
- 환경구축
  - celery task runner
  - rabbitmq message queue / broker
  - celery를 돌릴 추가적인 서버
- AwesomeTitle의 package 화
- #84 AwesomeTitle의 설정을 python manage.py config generate 로 생성할 수 있는 명령
