### ISSUE TITLE
닉네임 알림이 메뉴를 가려서 거슬려요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#83]
![image](https://cloud.githubusercontent.com/assets/17292957/13546448/bd4d3f7c-e2f1-11e5-8168-59237256608b.png)

닉네임 알림이 한번 뜨면 사라지지 않아서 다른 메뉴를 가려요! [X] 버튼이 있었으면 좋겠어요

**Comment by jmg7173** [comment]
닉네임 알림은 내페이지에 들어갔을 때 수정아래에 뜨게하는건 어떨까요!

**Comment by yunitto** [comment]
한번 해볼게요!!

**Comment by minhoryang** [comment]
앗! 쉽진않겠지만, 잘부탁드려요~!!

**Comment by minhoryang** [comment]
http://stackoverflow.com/questions/23096060/why-bootstrap-doesnt-use-an-x-icon-for-the-close-button
이런 사이트가 있네요.

**Comment by minhoryang** [comment]
``` html
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
```

[popover에 대한 설명](http://v4-alpha.getbootstrap.com/components/popovers/)
