### ISSUE TITLE
사이트를 이용하다가 로그아웃이 돼요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#88]
닉네임 추천 후에 리다이렉션되는 화면을 보면 로그아웃이 되어있어요!

**Comment by minhoryang** [comment]
고쳤어요 ;ㅅ;ㅠㅠ #84 번에서 SECRET_KEY를 매번 킬 때마다 랜덤으로 초기화하게해서, 서로 쿠키공유가 안됬던것 같아용.
