### ISSUE TITLE
별명 추천 DB

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#9]

**Comment by tmdghks0612** [comment]
오레와 별명 추천데스요!!

**Comment by minhoryang** [comment]
http://emailregex.com/

**Comment by JimJeon** [comment]
Q. 별명의 길이는 얼마로 할까요?

**Comment by minhoryang** [comment]
50글자

**Comment by tmdghks0612** [comment]
량민호씨 이거 db에 있는 정보 끌어다 쓰는 거 잘 모르겠어요

**Comment by tmdghks0612** [comment]
끝났습니다아

**Comment by minhoryang** [comment]
URL을 보기좋게 바꿔주세욧!

**Comment by minhoryang** [comment]
@tmdghks0612 소환!

**Comment by tmdghks0612** [comment]
네? 저요?

내 삼성 디바이스에서 보냈습니다

-------- 원본 메시지 --------
발신: Minho Ryang notifications@github.com 
날짜: 2016/02/24  오후 9:45  (GMT+09:00) 
수신: minhoryang/AwesomeTitle AwesomeTitle@noreply.github.com 
참조: tmdghks0612 dreamspidersh@gmail.com 
제목: Re: [AwesomeTitle] 별명 추천 DB (#9) 

@tmdghks0612 소환!
