### ISSUE TITLE
사진 파일 업로드시 미리 사진을 볼 수 있었으면 좋겠어요

### ISSUE THREAD

**Issue by yunitto** [minhoryang/AwesomeTitle#90]
Choose File 한 후에 선택한 사진이 실제 프로필에 어떻게 보여지는지 미리 볼 수 있었으면 좋겠어요.

**Comment by minhoryang** [comment]
+1

**Comment by minhoryang** [comment]
이거 @tmdghks0612 승환이랑 같이 살펴보았는데요 ㅠㅠㅠ 불가능할 것 같아요 ㅠㅠㅠㅠㅠㅠ
미안해요.. 다른 방안이 생각나기 전 까지 조금 미룰게요 ㅠㅠ
