### ISSUE TITLE
규모가 슬슬 커지니까, 테스트 코드도 필요합니다.

### ISSUE THREAD

**Issue by minhoryang** [minhoryang/AwesomeTitle#91]
어떤 코드를 추가하기 위해서는, 그 코드를 검증하는 테스트도 같이 추가해야합니다.
Flask를 테스트하는 두가지 방법이 있다고 하는데요.
[Flask Test Document](http://flask.pocoo.org/docs/0.10/testing/)
[Flask-Testing Module](https://pythonhosted.org/Flask-Testing/)

우선 테스트를 할 수 있도록 MySQL DB(서버가 필요함) 뿐만아니라 SQLite DB(파일로 대신함)를 사용할 수 있도록 패치를 추가했습니다.
6985c34b0f0b791c5f97425900c2cc3f45639d3e (config/upgrade)
282f1e77500384ec7bac3458ea3235741c625a7f (downgrade)
e161c8b1437beb64e29ec43eb93dab61f2f0cd25

**Comment by juice500ml** [comment]
우왕! 같이 만들어요 저 SP 다했어욬ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
#93 패키지로 묶었어요!! 29d071f283c47abe00ee73f90532b3b019e49470
테스트 코드는 tests/ 에 들어갈 거에요!
