### ISSUE TITLE
메인페이지에 오타

### ISSUE THREAD

**Issue by taeguk** [minhoryang/AwesomeTitle#98]
릴리즈 업적관리 사비스..는 역시 노린거겠죠? ㅋㅋㅋㅋ

**Comment by yunitto** [comment]
넵

**Comment by minhoryang** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by JimJeon** [comment]
+1 ㅋㅋㅋㅋㅋ
