### ISSUE TITLE
MITM공격에 따른 password 노출 취약점

### ISSUE THREAD

**Issue by taeguk** [minhoryang/AwesomeTitle#99]
![aa](https://cloud.githubusercontent.com/assets/9107889/13836931/d2b8b42a-ec49-11e5-969a-909650835933.PNG)
회원가입하는 부분에서 password를 암호화하지 않아 네트워크 상에서 중간자공격을 당할 시, password가 그대로 노출되는 취약점이 있습니다. (로그인, 비밀번호 변경 부분에도 같은 취약점 존재)
해결방법은 sha512같은 단방향 해쉬 알고리즘을 사용하여 password를 암호화한 후 서버로 전송하면 됩니다.
http://pajhome.org.uk/crypt/md5/sha512.html
등을 이용하여 javascript단에서 form 전송 시 password를 sha512로 hash해주면 좋을 것 같습니다.

**Comment by minhoryang** [comment]
@taeguk 헤헤! 우리는 letsencrypt로 https를 걸어버릴 예정이에요! 
그래도 sha512가 필요할까요?
https와 cert pin을 건다면?

**Comment by taeguk** [comment]
@minhoryang 제 생각에는 그래도 client단에서 비밀번호는 hash를 해야된다고 생각해요.
Server는 무슨 일이 있더라도 유저의 비밀번호 원문을 알 수 있으면 안되요. https를 사용할 경우, server는 암호화된 유저의 password를 복호화하여 원문을 알아 낼 수 있고 만약 server가 해킹당한 상황이라면 이때 유저들의 password는 고스란히 해커의 손에 넘어가고 다른 사이트에 적용시켜 유저의 피해가 야기될 수 있기 때문이죠~
따라서 애초에 password같은 정보는 그 누구도 원문을 알 수 없도록, client에서 빠져나올 때 hash하는 것이 옳다고 생각합니다...ㅎㅎㅎ

**Comment by minhoryang** [comment]
저희가 전달받은 password는 salt와 pepper가 칠해져 bcrypt로 해슁되어있어요!
- 회원가입
  https://github.com/SGCSRelease/AwesomeTitle/blob/master/user.py#L75
- 로그인
  https://github.com/SGCSRelease/AwesomeTitle/blob/master/user.py#L160-L163

**Comment by taeguk** [comment]
@minhoryang 하지만 server측에서 db에 저장하기 전에 hashing하는 거라서 client와 server가 통신할 때 사이에서 패킷을 감청하면 password 원문을 알아낼 수 있어요!

**Comment by minhoryang** [comment]
그걸 https로 막겠다는거지요! 그래도 안되나요?

**Comment by taeguk** [comment]
@minhoryang https를 해도 Server가 해킹됐을 경우에는 password 원문이 노출되는 것을 막을 수 없어요 ㅠㅠ https는 'hash'가 아니라 '암호화' 이기 때문에 결국 server에서 복호화가 되는데, 이때 서버가 해킹된 상태이면 해커가 틈새를 노려 password 원문을 빼내갈 수 있죠.. 
https만으로도 보안이 어느정도 강력해질테지만 제일 완벽한 건, client단에서 javascript로 hashing하는 것 같애요~

**Comment by JimJeon** [comment]
당신들.... 넘나 멋져요!!!

**Comment by minhoryang** [comment]
지금 taeguk.reluv.me도 보면 reversed proxy로 .105에서 .104를 바라보게되어있고,
.104는 외부에서 접근이 안되니까 괜찮다고생각해요.
SQLAlchemy는 SQL Injection을, Jinja2는 XSSInjection을 막아줘요. 한번 이쪽을 시도해봐주세요.

**Comment by minhoryang** [comment]
지금은 taeguk이랑 같은 linux를 공유하지만, 실서비스시 (나중에는) 당연히 별도의 vm으로 구분되어있을거에요.
Https 트래픽도, .105에서 http로 까져서 .104에서 서비스하는게 아니라,
.104까지 끝까지 https로 보낼거에요.
진짜 그때는 "서버가해킹됬을때"가 문제가되는거죠.

**Comment by minhoryang** [comment]
JS해싱은, 사실 더 위험한 방식이라고 생각하는데, 우선 표준이 아니구요. 암호화기법자체를 노출하는거라, 해킹 이후에 콜루젼찾기가 더 쉬워요

**Comment by minhoryang** [comment]
다른 클라이언트 이식도 힘들구요.

**Comment by minhoryang** [comment]
JS암호화스크립트를 믿을 수 있는지도 모르겠어요. 적어도 bcrypt는 openssl을 이용하거든요. ssh도 https두요

**Comment by minhoryang** [comment]
서버를 해킹해서 접근할 수 있다면, 제가 노릴건 해싱이아니라 클라코드수정일거에요.

**Comment by minhoryang** [comment]
우리사이트뿐만아니라 다른사이트의 정보까지 순순히 뺃어올 수 있는데요 ㅎㅎ

**Comment by minhoryang** [comment]
http://security.stackexchange.com/questions/8596/https-security-should-password-be-hashed-server-side-or-client-side
http://stackoverflow.com/questions/3715920/about-password-hashing-system-on-client-side

**Comment by taeguk** [comment]
음 https를 이용하는 것과 client단에서 javascript hashing하는 것중 어떤게 보안이 뛰어날 지를 비교하려는 것은 아니에요.
단순히 보안 측면에서
지금 코드 < javascript로 password를 hashing하는 것
https < https + javascript로 password를 hashing하는 것
이라고 생각하기 때문에 javascript를 이용해서 password를 hashing하는 게 옳다고 생각해요

**Comment by taeguk** [comment]
어떻게 보면 99%냐 99.9%냐의 얘기같은데,
서버가 해킹당했을 때 해커가 무엇을 할 지 가연성을 따지는 것을 떠나서, 만약 그것이 user의 raw password를 알아내는 것이라고 가정했을 때, javascript로 hashing을 한 경우가 보안이 더 뛰어날 것이라는 점이에요~ 해커가 레인보우테이블을 이용하든 콜리젼을 찾든 해야할 작업이 더 늘어나기 때문에요..

**Comment by juice500ml** [comment]
오.. 오오오... 뭐야 여기..

**Comment by minhoryang** [comment]
음. 우리는 https를 꼭 도입할 거에요. 그래야만해요. 개인정보를 관리하기 때문이에요. 지금은 alpha/beta니까 괜찮은거구요. 나중에 주소록기능을 도입하게 되는 순간, 아니 그보다 전에 https로 넘어갈 거에요.

**Comment by minhoryang** [comment]
https가 필수이기 때문에, 문제는 'javascript로 password를 hashing하는 것'을 할 필요가 있는가? 로 바뀌어요.

**Comment by minhoryang** [comment]
```
"javascript로 hashing을 한 경우가 보안이 더 뛰어날 것이라는 점이에요"
```

보안이 뛰어나 지지 않아요. 해커가 더 귀찮아지는 것 뿐이지요.
이는 보안이 뛰어나다고 말할 수 없어요.
고로 

```
"어떻게 보면 99%냐 99.9%냐의 얘기같은데,"
```

가 아니에요.

반대로 우리가 사용한 js라이브러리의 취약점이 밝혀진다고 가정해보면, 그 때는 보안이 무너진거죠.
(wordpress나 phpmyadmin처럼 많이 쓰는 곳에 공격이 더 자주 일어나는 이유를 생각해보면되요. github에서 그 라이브러리를 사용하는 곳을 찾은다음, 공격을 시도하면 되죠.)

이렇게되면 99%(해커가 우리의 존재를 아느냐) vs 0%(모르느냐)로 바뀌어요.

```
https + javascript로 password를 hashing하는 것
```

이 상황에서는 js라이브러리의 취약점이 공개된다면 https의 노력에도 불구하고, 패스워드는 뚤리게 되는거죠.

**Comment by minhoryang** [comment]
반대로는 우리가 사용한 js라이브러리의 취약점이 밝혀진다고 가정해보면, 그 때는 보안이 무너진거죠.
(wordpress나 phpmyadmin처럼 많이 쓰는 곳에 공격이 더 자주 일어나는 이유를 생각해보면되요.)

**Comment by minhoryang** [comment]
그러면 다시 생각해봅시다.

**Comment by minhoryang** [comment]
1. mitm 문제는 https가 해결해 줄 것.
2. perhaps
   - 서버가 뚤리는 것을 걱정하는 것 보다, 신뢰할 수 없는 JS sha512라이브러리를 안쓰는게 더 쉬움.
     - 차라리 https://www.w3.org/TR/WebCryptoAPI/ 를 써요.
     - http://caniuse.com/#search=crypto

**Comment by taeguk** [comment]
음... 어차피 client <---https---> server 같은 식으로 client(browser)와 server가 통신할때 https를 사용하게 되는 건데, hashing을 하고 안하고의 차이는 client가 server로 넘기는게 raw password 냐 hashed password 냐의 문제기 때문에 만약 js라이브러리가 취약하고 뚫린다고 하더라도 보안성이 hashing을 사용하지 않을 때랑 똑같아 질 뿐이지 더 나빠지진 않아요.
https와 hashing이 사용되는 구간이 서로 완전히 다르기 때문에 hashing이 뚫렸다고 하더라도 https가 뚤리지는 않아요.

**Comment by minhoryang** [comment]
js가 취약해서 뚫리면, http를 바라보지 않고, 클라만 후킹해도, password를 얻을 수 있지 않나요?
https는 뚤리지 않죠. 하지만 password는 뚤렸습니다. ㅠㅠ

**Comment by minhoryang** [comment]
hash(hash(pw))도 의미가 없습니다 ;ㅅ;ㅠ

**Comment by minhoryang** [comment]
https://crackstation.net/hashing-security.htm

``` markdown
IMPORTANT WARNING:
If you are thinking of writing your own password hashing code, please don't!.
It's too easy to screw up.
No, that cryptography course you took in university doesn't make you exempt from this warning.
This applies to everyone:
DO NOT WRITE YOUR OWN CRYPTO!
The problem of storing passwords has already been solved.
Use either use either phpass, the PHP, C#, Java, and Ruby implementations in defuse/password-hashing, or libsodium.
```

**Comment by taeguk** [comment]
음 제가 말하고 싶은 건 https는 클라이언트부터 서버까지 데이터를 안전하게 전송해주는 역할을 하는 건데 결국에 서버에 전송되는게 raw password라는 거죠. 즉, 서버에서 처리되는 동안은 raw password 상태라는 것이고 서버가 안전하다고 해도 굳히 서버에서 유저의 raw password를 알아야 할 필요는 없죠. 그렇기 때문에 그냥 클라에서 서버로 raw password를 전송하지 않고, hash를 한 hashed password를 전송하게 되면 이러한 이슈를 해결할 수 있다는 거죠.

**Comment by minhoryang** [comment]
"서버에서 유저의 raw password를 알아야 할 필요는 없죠." 이 문제는 의미 있는 문제이죠!
그런데 그렇다고 모르는 js를 들고오면 안됩니다. (작성자가 정말 뛰어난 사람이래도, openssl이나 libsolium, nacl 등이 존재하는 이유는 따로있지요. 털리면 저에게 고지라도 오거든요.)

**Comment by taeguk** [comment]
password가 필요한 건 단순히 인증 절차일 뿐인데, raw password를 사용할 필요는 없죠. raw password는 다른 사이트들에서도 사용하고 있을 수 있기 때문에 최대한 그 존재가 숨겨져야한다고 생각해요. 그렇기때문에 그냥 javascript로 hashing을 한채로 서버에 전송하는 게 옳다고 생각하는 이유에요.

**Comment by minhoryang** [comment]
hash(pw)가 콜루젼을 일으키지 않는다는 건 아직도 도전과제이죠.
하지만 hash(hash(pw))가 콜루젼을 일으키지 않는다는 건 위의 주장보다 훨씬 위험한 생각이에요.
http://programmers.stackexchange.com/questions/115406/is-it-more-secure-to-hash-a-password-multiple-times

**Comment by minhoryang** [comment]
![2016-03-18 1 17 54](https://cloud.githubusercontent.com/assets/1270855/13852827/44c83d30-eca7-11e5-8480-366a85c72830.png)

**Comment by taeguk** [comment]
아 제가 그 부분을 간과했네요....ㅠㅠ 음 그런 측면에서는 적용안하는게 날 것 같아요

**Comment by minhoryang** [comment]
+_+ 정말 순간적으로 공부 많이했습니다. 한수 배웠어요.

**Comment by minhoryang** [comment]
서버를 믿을 수 없다면, 클라우드 비즈니스는 망해야합니다 .... 그건 자신의 서버도 아니고, 남의 모르는 곳에 있는 서버이며, 심지어 또 쌩판 모르는 사람과 같이 써요.

**Comment by minhoryang** [comment]
릴리즈서버가 위험하다는 주장은 충분히 가능성 있습니다.

**Comment by minhoryang** [comment]
사실 나도 위험하게 쓰는데... (사실 위험하길 바람 조금)

**Comment by minhoryang** [comment]
서버가 해킹되는 것 (openssh/openssl취약점) vs 서버가 해킹되는 것 (일반 사용자의 비번노출)

**Comment by minhoryang** [comment]
요즘 안그래도 단순 인증절차라는 이야기가 많아서 passwordless라는 운동도 많이 펼쳐지고 있어요
https://passwordless.net/
https://auth0.com/passwordless

이는 sms나 메일기반으로 로그인하자는건데요 (클릭으로 로그인)

**Comment by minhoryang** [comment]
사실 한국식 (너네과실이야)랑 저는 비슷하다고 생각하는게 조금 있어서. 아직은 판단보류입니다.

**Comment by minhoryang** [comment]
https 스니핑보다,, 안드로이드 문자 뚫기가 더쉬워요.

**Comment by minhoryang** [comment]
메일 사이트는 단골 타겟이구요.

**Comment by juice500ml** [comment]
와우 :+1: for hash(hash())

**Comment by taeguk** [comment]
그건 그렇죠 ㅋㅋㅋㅋ 저는 단지 raw password는 최대한 보호되어야된다는 생각에 그런 주장을 펼친건데 double hashing collision에 대해서 간과했네요. 
처음에 이슈올릴때는 https가 아닌 상황에서 password가 그대로 노출되서 중간자공격에 대한 위험성이 collison문제보다 크다 생각했는데 https를 통해 중간자공격에 대해 방어를 하고 난 상태에서는 server측의 신뢰여부에 대한 위험성이 collision문제 보다 더 크다고는 말할수없을거같아요

**Comment by minhoryang** [comment]
"서버의 관리자에게 password가 노출 될 것이다"는 실제로 말이 되는 말이라서요.
그래서 요즘은 배포용 서버와 개발용 서버를 따로둡니다. CI (Continuous integration) 이나 CD (Continuous Deploy) 에 대해서도 공부할만해요. 제 요즘 관심사입니다. -> DevOps

우리도 당연히! 이렇게 갈거에요.
http://12factor.net/

**Comment by taeguk** [comment]
음 근데 double hashing 이 정식용어는 아닌거같고... hash(hash()) 이걸 뭐라고 불러야할지 모르겠네요 ㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
multiple hashing이죠뭐ㅎㅎ

**Comment by taeguk** [comment]
음 근데 너무 순간적으로 판단을 제가 내린 거 같은데 다시 생각해보니 multiple hashing이 collision에 대해서 더 위험하다는 근거가 있을까요?? 
http://stackoverflow.com/questions/348109/is-double-hashing-a-password-less-secure-than-just-hashing-it-once

**Comment by minhoryang** [comment]
음 저도 생각중입니당.

**Comment by minhoryang** [comment]
단방향함수 두번이라고 생각하니 아니라고 생각이되네요. 잠깐만요.

**Comment by minhoryang** [comment]
콜루젼에서는 위험하지 않네요.

**Comment by taeguk** [comment]
아아 제 생각엔 hashing을 과하게 중첩하면 collision이 많아질 것 같긴해요

**Comment by minhoryang** [comment]
그런데 레인보우어택에 취약해지겠네요.

**Comment by minhoryang** [comment]
두번째 해싱에서 인풋에 리미테이션이 있잖아요? (표현가능성?)

**Comment by minhoryang** [comment]
전단계의 해싱이 표현가짓수를 줄이는거죠.

**Comment by minhoryang** [comment]
결국 가장 약한 부분이 전체의 가장 약한부분이 되겠네요.

**Comment by minhoryang** [comment]
이건 어떻게 생각하세요?

**Comment by taeguk** [comment]
제 생각을 정리하면, hashing을 중첩할 수록 collision 가능성은 커진다 이고,
근데 잘 모르겠는 점은 sha512를 한 번 더 한다고 해서 collision 가능성이 유의미하게 커질 것 이냐에요.
사실상 거의 똑같다고 하면 제가 언급한 client단에서의 password hashing이 옳다고 생각되구, 만약 유의미한 차이가 있다고 하면 옳지 않다고 생각되요.

**Comment by taeguk** [comment]
http://stackoverflow.com/a/12262905
이 답변이 약간 제가 고민하는 거에 대한 다른 사람의 생각이네요.

**Comment by minhoryang** [comment]
외부(수제) JS라이브러리를 써서 서버를 신뢰하지 않는 것 vs 외부(수제) JS라이브러리를 신뢰하지 않는 것.
의 차이 아닐까요?
1. 아무도 책임지지않아요
2. 포터블하지않아요
3. 포팅하다가 문제가 더 생길 수도 있어요.
4. 사용하다가 문제가 더 생길 수도 있어요.

저는 클라이언트를 믿는 것 보다, 서버를 믿는 편이에요.
서버가 뚫리는 것 보다, 클라이언트가 위태로울 확률이 더 크다고 봐요.
갑자기 궁금해졌는데 client단에서 JS를 다른 라이브러리로 바꿔치기당하는건 어떻게 생각해요?

**Comment by minhoryang** [comment]
'만약'을 가지고 말하기엔, 외부(수제) JS라이브러리는 저에게 '만약'의 영역이 아니네요.
WebCrypto, NaCl, OpenSSL libressl 등등 우리에게는 저것 말고도 선택지가 정말 많아요.
그리고 서버사이드도 JS보다 우리가 취할 수 있는 선택지가 정말 많아요.
VM/Vlan/OpenID Connect/OAuth2/Single Sign On/Facebook-Twitter Login/ ...

**Comment by taeguk** [comment]
client단에서 조작이 일어났다는 건 총 2가지 경우겠죠.
client가 해커라서 조작을 했을 경우 -> service 제공의무가 없다.
client가 해킹당한 상태 -> 이 경우는 어쩔수없는거죠

**Comment by minhoryang** [comment]
문제는 우리가 아니에요.
평문pw를 평문으로 http://library.sogang.ac.kr에 쿼리를 날리는 R9.4가 있는데...... 지금도그러나.

**Comment by minhoryang** [comment]
- 3. js의 작동이 chrome이나 egde나 firefox에 따라 다르다.
- 4. 특정 IE에 따라 다르다
- 5. 깔려있는 Extensions에 따라 다르다.

**Comment by taeguk** [comment]
ssl 라이브러리같은 경우는 client와 server 사이 통신 레벨에서 적용하는 거니까 논의 대상이 아닌거 같구,,, 제가 언급한 라이브러리는 굳히 이걸 사용할 필요는 없고, sha512를 지원하는 다른 믿을 만한 javascript code가 있다면 그걸 사용하면 되요!

**Comment by minhoryang** [comment]
- 6. JS의 작동이 CPU에 따라 다르다.

**Comment by taeguk** [comment]
음... 암호화의 경우 논리적인 연산만 있는데 browser나 cpu에 따라 처리 결과가 다를 수가 있을까요?? browser rendering관련 한거라면 차이가 있을 수 있겠지만...
이건 library의 신뢰를 떠나서 javascript를 신뢰못하는 거 아닐까요 ㅠㅠ

**Comment by minhoryang** [comment]
자바스크립트는 튜링 컴플리트 해요. 하지만 구현은 그렇지 않아요..

**Comment by taeguk** [comment]
구현이 js 엔진을 말씀하시는거에요? 아니면 library말씀하시는거에요?

**Comment by minhoryang** [comment]
js엔진이요.

**Comment by minhoryang** [comment]
사람들은 js엔진구현에 스피드테스트는 해요.
그런데 신뢰는 하지 않아요.

**Comment by taeguk** [comment]
음 그러면 web의 동작자체가 신뢰적이지 않을 수 있다는 건데....흠...

**Comment by minhoryang** [comment]
이미 신뢰적이지 않아요.... OTL

**Comment by taeguk** [comment]
그러면 어떡하죠... MFC를 해야하나요? ㅋㅋㅋㅋ

**Comment by minhoryang** [comment]
Neither MFC...

**Comment by minhoryang** [comment]
그래서 나온게 Adobe Flash/Silverlight/ActiveX 등이 있습니다.
결국 다 똥이죠.

**Comment by minhoryang** [comment]
그래서 있는 라이브러리를 쓰자는겁니다.

**Comment by taeguk** [comment]
음 근데 잘 믿기지가 않네요. 관련 자료가 있을까요?? ㅠㅠ

**Comment by taeguk** [comment]
근데 제가 소개한 라이브러리가 아닌 다른 걸 쓰더라도 결국엔 javascript library를 써야해요 
client에서 동작해야하기 때문에

**Comment by minhoryang** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1254806

**Comment by minhoryang** [comment]
https://github.com/ozaki-r/arm-js/issues/10

**Comment by minhoryang** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=1181

**Comment by minhoryang** [comment]
https://bugs.webkit.org/show_bug.cgi?id=85076

**Comment by minhoryang** [comment]
정확히 그 쪽에서 문제가 나는 경우를 찾고싶은데. 예전 비트코인 커뮤니티에서 본걸 찾기가 힘드네요 ㅠㅠ

**Comment by minhoryang** [comment]
못찾겠습니다. 잘못된 주장이라고 생각해주세요.

**Comment by taeguk** [comment]
음..그러면 js가 불안정할 수 있으므로 password hashing같은 critical한 기능을 넣지 말자?? 가 주장이신건가요?? ㅎㅎㅎㅎ

**Comment by minhoryang** [comment]
http://arxiv.org/abs/1502.07373

**Comment by minhoryang** [comment]
우선 네. js를 믿지 않습니다 ㅠㅠ

**Comment by minhoryang** [comment]
그런데 이런 의견들도 있네요 
https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/

```
WHAT'S A "MALLEABLE RUNTIME"? WHY ARE THEY BAD?
```

https://tonyarcieri.com/whats-wrong-with-webcrypto

**Comment by taeguk** [comment]
근데 javascript sandbox escaping같은 작정하고 노려진 js엔진 버그나 취약점은 당연히 있는건데 (엔진도 프로그램이니까)
형 말씀대로 잘 알려진 혹은 믿을민한 js hashing library를 사용하면 괜찮은거 아닌가요??

**Comment by minhoryang** [comment]
libsodium이 믿을만한 라이브러리긴 한데요. libsodium.js는 믿을만한 라이브러리는 아니에요.
libsodium.js로 컨버팅 하면서 신뢰성이 사라졌다고 생각해요.

**Comment by minhoryang** [comment]
https://gist.github.com/jo/8619441

**Comment by minhoryang** [comment]
컨버팅된 결과물은, 버전 글리치가 생긴다고 생각하고 있어요.

**Comment by taeguk** [comment]
음 그렇군요... 근데 사실 hash algorithm '구현'은 복잡한 엔지니어링 이슈같은게 물려있는게 아니라 그냥 수학적인 수식을 코드로 옮길뿐인데 버그가 있을 가능성이 거의 없지 않을까요??

**Comment by minhoryang** [comment]
https://www.bouncycastle.org/

**Comment by minhoryang** [comment]
수식을 코드로 옮기면, 느리죠. 그래서 옵티마이즈를 합니다. 문제는 거기서 발생해요. 아 JS는 그보다 조금 더 먼저군요.

**Comment by minhoryang** [comment]
http://j.mearie.org/post/98388202823/telegram
http://j.mearie.org/post/103767495933/high-level-understanding-of-cryptography
http://j.mearie.org/post/109667188208/abstract-and-concrete

**Comment by minhoryang** [comment]
http://crypto.stackexchange.com/questions/10200/is-javascript-rsa-signing-safe

**Comment by minhoryang** [comment]
http://stackoverflow.com/questions/7350885/how-secure-is-javascript-encryption

**Comment by minhoryang** [comment]
자기전에 제가 설득안당하려고하는(?!?) 고집부리는 영역을 좁혀보면
1. JS안믿는다
로 좁혀지겠네요 ;ㅅ;ㅠㅠ

어? 서버에 raw가 전송되는걸 믿지 않는데 https는 믿으시나요?!

**Comment by taeguk** [comment]
엇 마지막줄이 무슨 뜻이신지 잘 모르겠어요 ㅠㅠ

**Comment by taeguk** [comment]
제 의견을 정리하면 일단 여전히 client단에서 javascript로 password hashing을 하는게 옳다고 판단합니다.
하지만 javascript hash 구현 및 동작이 신뢰가능한지가 실질적인 도입에 있어서 변수가 될 수 있을 것 같습니다.
그래도 저는 도입하는게 옳다고 생각하는게, 만약 rsa같은 경우는 또 모르겠지만 이 경우는 hash라서 만약 미세한 버그가 있어서 hash가 뚫린다 하더라도 보안성이 도입안했을때랑 똑같애지기 때문입니다. (미세할것으로 추정되는 db에 저장되는 해시값의 collision확률 증가를 제외하면) 미세한 버그가 아닌 아예 똑같은 인풋을 넣었는데 그때그때 다른 해쉬값이 나오는등의 엉터리 구현들만 js 라이브러리들에 존재하리라고는 생각하지 않아서요 ㅠㅠ

**Comment by minhoryang** [comment]
다음번에 더 나은 이야기가 될 것 같아요. 저도 계속 생각하고 있을게요.

**Comment by taeguk** [comment]
민호형은 신뢰하지 못하시지만 ㅠㅠ 제가 사용하고 있는 http://pajhome.org.uk/crypt/md5/sha512.html
의 코드만 훏어보더라도 크게 버그가 생길만한 코드가 없어서요 ㅠㅠㅠㅠㅜㅠㅠ

**Comment by taeguk** [comment]
알겠습니다 ㅎㅎ 오래 토론했네요 안녕히 주무세요!!!!

**Comment by minhoryang** [comment]
왜 저를 안 의심해요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저부터의심해욬ㅋㅋㅋ
저는... 코드를 훑어보고 버그를 발견하는 능력까진 안되요... OTL

**Comment by minhoryang** [comment]
잘려고 샤워하고왔는데 갑자기 든 생각이
전 password를 완전무결하다고 생각하지 않네요.
그러니까 절대 raw password가 노출될 일이 없다고 생각하지 않아요.
raw password도 노출될 수 있어요.
그래서 시중에 많은 password 관리 툴들이 있지 않을까요. (lastpass, auth0, logmein, keepass, dashlane, 1password, enpass, ...)
**저런 툴을 쓰는 사람들은 무엇을 믿고, 저기에 제 password를 맡길까요?**

**Comment by minhoryang** [comment]
제 fb password 는 참고로 http로 (아무나) 접속할 수 있는 (저는 외우지 않지만, 링크가 있긴 해요) 1024바이트의 os.random입니다. - _-;; (누가 url에 방문했는지 확인하지도 않아요. 기능도 없고.)

**Comment by minhoryang** [comment]
![2016-03-18 3 42 49](https://cloud.githubusercontent.com/assets/1270855/13857079/9ba96ed0-ecbb-11e5-9b88-38f5e6ff5d39.png)

**Comment by minhoryang** [comment]
SHA1이긴 하지만..
http://pajhome.org.uk/crypt/md5/sha1.html 2.2버전의 코드
https://dl.packetstormsecurity.net/papers/general/advanced-crack.pdf (pg.9) 2.1버전의 취약점.
